---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/app
  - ../../components/redis
  - govee-sealed-secret.yaml

namespace: "govee-web"
namePrefix: "govee-web-"
images:
  - name: "mattcl/govee-web"
    newTag: "0.1.5"
  - name: "docker.io/bitnami/redis"
    newTag: "6.2.12"
configMapGenerator:
  - name: app-config
    envs:
      - "app-config.env"
