---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    spec:
      containers:
        - name: app
          image: "mattcl/govee-web:0.1.1"
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: "app-config"
            - secretRef:
                name: "govee-web-govee-secret"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
            failureThreshold: 2
            terminationGracePeriodSeconds: 5
