---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  revisionHistoryLimit: 3
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    spec:
      containers:
        - name: app
          image: "mattcl/govee-web:0.1.0"
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: "app-config"
            - secretRef:
                name: "govee-web-govee-secret"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
