---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kong-ingress
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: govee-web-rewrite-path
  labels:
    traffic-type: internal
spec:
  ingressClassName: kong
  rules:
    - host: api.hl.ancalagon.black
      http:
        paths:
          - path: /govee/(.*)
            pathType: Prefix
            backend:
              service:
                name: govee-web-svc
                port:
                  number: 80

---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rewrite-path
config:
  replace:
    uri: '/api/v1/$(uri_captures[1])'
plugin: request-transformer
